---
image: docker:stable
services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker version

.build:
  stage: build
  script:
    - |
        docker build --pull \
        --build-arg BASE_IMAGE_VERSION=$BASE_IMAGE_VERSION  \
        --build-arg JULIA_MAJOR=$JULIA_MAJOR \
        --build-arg JULIA_VERSION=$JULIA_VERSION \
        --build-arg PLJULIA_REGRESSION=YES \
        -t pljulia .
    - docker images pljulia
    - docker images $BASE_IMAGE_VERSION

# ---------------------------------
# --------- Julia Stable ----------
# ---------------------------------

pg18-jl1.12.6:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:18'
    JULIA_MAJOR: '1.12'
    JULIA_VERSION: '1.12.6'

pg17-jl1.12.6:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:17'
    JULIA_MAJOR: '1.12'
    JULIA_VERSION: '1.12.6'

pg16-jl1.12.6:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:16'
    JULIA_MAJOR: '1.12'
    JULIA_VERSION: '1.12.6'

pg15-jl1.12.6:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:15'
    JULIA_MAJOR: '1.12'
    JULIA_VERSION: '1.12.6'

pg14-jl1.12.6:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:14'
    JULIA_MAJOR: '1.12'
    JULIA_VERSION: '1.12.6'

# ------------------------------
# --------- Julia LTS ----------
# ------------------------------

pg18-jl1.10.11:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:18'
    JULIA_MAJOR: '1.10'
    JULIA_VERSION: '1.10.11'

pg17-jl1.10.11:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:17'
    JULIA_MAJOR: '1.10'
    JULIA_VERSION: '1.10.11'

pg16-jl1.10.11:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:16'
    JULIA_MAJOR: '1.10'
    JULIA_VERSION: '1.10.11'

pg15-jl1.10.11:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:15'
    JULIA_MAJOR: '1.10'
    JULIA_VERSION: '1.10.11'

pg14-jl1.10.11:
  extends: .build
  allow_failure: false
  variables:
    BASE_IMAGE_VERSION: 'postgres:14'
    JULIA_MAJOR: '1.10'
    JULIA_VERSION: '1.10.11'

# -----------------------------------
# --------- Julia Upcoming ----------
# -----------------------------------

pg18-jl1.13.0-rc1:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:18'
    JULIA_MAJOR: '1.13'
    JULIA_VERSION: '1.13.0-rc1'

pg17-jl1.13.0-rc1:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:17'
    JULIA_MAJOR: '1.13'
    JULIA_VERSION: '1.13.0-rc1'

pg16-jl1.13.0-rc1:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:16'
    JULIA_MAJOR: '1.13'
    JULIA_VERSION: '1.13.0-rc1'

pg15-jl1.13.0-rc1:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:15'
    JULIA_MAJOR: '1.13'
    JULIA_VERSION: '1.13.0-rc1'

pg14-jl1.13.0-rc1:
  extends: .build
  allow_failure: true
  variables:
    BASE_IMAGE_VERSION: 'postgres:14'
    JULIA_MAJOR: '1.13'
    JULIA_VERSION: '1.13.0-rc1'
