#!/bin/bash
set -o errexit

# simple test matrix - for local testing

DOCKER_DIR=`dirname $BASH_SOURCE[0]`
DOCKER_DIR="${DOCKER_DIR}/.."

# Julia 1.6.1 + Postgres:13
docker build --pull \
   --build-arg BASE_IMAGE_VERSION=postgres:13  \
   --build-arg JULIA_MAJOR=1.6 \
   --build-arg JULIA_VERSION=1.6.1 \
   -t pljulia:pg13-jl1.6 $DOCKER_DIR

# Julia 1.0.5 + Postgres:12
docker build --pull \
   --build-arg BASE_IMAGE_VERSION=postgres:12  \
   --build-arg JULIA_MAJOR=1.0 \
   --build-arg JULIA_VERSION=1.0.5 \
   -t pljulia:pg12-jl1.0 $DOCKER_DIR

# Julia 1.6.1 + postgis/postgis:13-3.1
docker build --pull \
   --build-arg BASE_IMAGE_VERSION=postgis/postgis:13-3.1  \
   --build-arg JULIA_MAJOR=1.6 \
   --build-arg JULIA_VERSION=1.6.1 \
   -t pljulia:pg13-pgis3.1-jl1.6 $DOCKER_DIR

# List docker images
docker images | grep pljulia
